server:
    port: 8083
spring:
    data:
        mongodb:
            #uri: mongodb+srv://fyauriba:fyauriba@cluster0.lds0o.mongodb.net/banca-account?retryWrites=true&w=majority
            #uri: mongodb://localhost:27018/banca-account
            host: mongo
            port: 27017
    cloud:
        discovery:
            enabled: true
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
eureka:
  instance:
     hostname: localhost
     #hostname: ms-eureka
     #hostname: eureka-service-contenedor
     prefer-ip-address: true
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
        defaultZone: http://${eureka.instance.hostname}:8087/eureka/
