server:
    port: 8082
spring:
    data:
        mongodb:
            host: mymongodb
            port: 27017
            authentication-database: admin
            database: banca-customer
            repository:
                enable: true
    cloud:
        discovery:
            enabled: true
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
eureka:
  instance:
     hostname: ms-eureka
     #hostname: eureka-service-contenedor
     prefer-ip-address: true
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
        defaultZone: http://${eureka.instance.hostname}:8087/eureka/
