server:
    port: 8082
spring:
    data:
        mongodb:
            host: host.docker.internal
            port: 27017
    cloud:
        discovery:
            enabled: true
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
eureka:
  instance:
     hostname: ms-eureka
     #hostname: eureka-service-contenedor
     prefer-ip-address: true
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
        defaultZone: http://${eureka.instance.hostname}:8087/eureka/
