server:
    port: 8086
spring:
    data:
        mongodb:
            uri: mongodb+srv://fyauriba:fyauriba@cluster0.alkipm8.mongodb.net/banca-movement?retryWrites=true&w=majority
            #uri: mongo
    cloud:
        discovery:
            enabled: true
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
eureka:
  instance:
     hostname: localhost
     #hostname: ms-eureka
     #hostname: eureka-service-contenedor
     prefer-ip-address: true
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
        defaultZone: http://${eureka.instance.hostname}:8087/eureka/
